language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost1.48-dev libboost-program-options1.48-dev libboost-wave1.48-dev libboost-system1.48-dev libboost-thread1.48-dev libboost-filesystem1.48-dev libboost-regex1.48-dev libreadline-dev libclang-dev libncurses5-dev
script:
  # Test that the TOC of the description is up to date
  - tools/gen_toc -i README.md -o - -t github | diff README.md -
  # Test the code
  - tools/clang_default_path > lib/extra_sysinclude.hpp
  - mkdir bin
  - cd bin
  # -DMETASHELL_DISABLE_CONSTEXPR (and its usage in the code) can be removed
  # when clang 3.1 or higher will be available on the CI servers
  - cmake .. -DCMAKE_CXX_FLAGS:STRING="-std=c++0x -Wall -Werror -pedantic -DMETASHELL_DISABLE_CONSTEXPR"
  - make
  - make test || (cat Testing/Temporary/LastTest.log && false)
  # Test that the documentation about the built-in pragmas is up to date
  - app/metashell --show_pragma_help | ../tools/replace_part -i ../README.md -o - -r - | diff ../README.md -
