language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y
      libprotobuf-dev
      libreadline-dev
      libclang-dev
      libncurses5-dev
      clang
      g++-4.8
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi
script:
  # Test the code
  - mkdir bin
  - cd bin
  - cmake .. -DCMAKE_CXX_FLAGS:STRING="-Werror" -DCLANG_STATIC=false -DCLANG_DEBUG=true -DCLANG_LIBRARYDIR=/usr/local/clang-3.4/lib -DNO_TEMPLIGHT=true
  - make -j2
  - make test || (cat Testing/Temporary/LastTest.log && false)
  # Determine the version of the underlying Clang binary
  - CLANG_BINARY="$((echo int | app/metashell --log l >/dev/null) && egrep -o 'Running Clang. .* -x' l | sed 's/Running Clang. //' | sed 's/ -x$//' | tail -1)"
  - echo "CLANG_BINARY=${CLANG_BINARY}"
  - ${CLANG_BINARY} -v
  # Run the system tests
  - test/system/app/core/metashell_core_system_test app/metashell -I../3rd/boost/include --
  # Test that the documentation about the built-in pragmas and mdb commands is up to date
  - app/metashell --show_pragma_help | ../tools/replace_part -i ../docs/reference/pragmas.md -m '<!-- pragma_info -->' -o - -r - | diff ../docs/reference/pragmas.md -
  - app/metashell --show_mdb_help | ../tools/replace_part -i ../docs/reference/mdb_commands.md -m '<!-- mdb_info -->' -o - -r - | diff ../docs/reference/mdb_commands.md -
