language: cpp
compiler:
  - gcc
  - clang
before_install:
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y
      libreadline-dev
      libclang-dev
      libncurses5-dev
      clang
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -y g++-4.8; export CXX="g++-4.8"; fi
script:
  # Test that the TOC of the description is up to date
  - tools/gen_toc -i README.md -o - -t github | diff README.md -
  # Test the code
  - mkdir bin
  - cd bin
  - cmake .. -DCMAKE_CXX_FLAGS:STRING="-Werror -DMETASHELL_DISABLE_TEMPLIGHT_TESTS" -DCLANG_STATIC=false -DCLANG_DEBUG=true -DCLANG_LIBRARYDIR=/usr/local/clang-3.4/lib
  - make VERBOSE=1 -j2
  - make test || (cat Testing/Temporary/LastTest.log && false)
  # Test that the documentation about the built-in pragmas and mdb commands is up to date
  - app/metashell --show_pragma_help | ../tools/replace_part -i ../README.md -m '<!-- pragma_info -->' -o - -r - | diff ../README.md -
  - app/metashell --show_mdb_help | ../tools/replace_part -i ../README.md -m '<!-- mdb_info -->' -o - -r - | diff ../README.md -
