os: Visual Studio 2017
image: Previous Visual Studio 2017

platform:
  - Win32

configuration:
  - Release

environment:
  matrix:
    - TESTS: unit
    - TESTS: internal
    - TESTS: templight
    - TESTS: clang
    - TESTS: msvc
    - TESTS: wave
    - TESTS: auto

install:
  - md bin\windows_%platform%
  - cd bin\windows_%platform%
  - appveyor DownloadFile https://github.com/metashell/templight_binary/releases/download/templight_c2fc38/templight_windows.zip
  - 7z -y x templight_windows.zip
  - appveyor-retry choco install nsis --version 2.50.0.20160103
  - cd ..\..

before_build:
  - md bin\windows_%platform%\metashell
  - cd bin\windows_%platform%\metashell
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" ..\..\..
  - cd ..\..\..

build_script:
  - set NO_TEMPLIGHT=1
  - set METASHELL_NO_DOC_GENERATION=1
  - "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\" x86"
  - build.bat
