os: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug
  - Release

install:
  - cd c:\projects\metashell\3rd\templight
  - appveyor DownloadFile https://github.com/sabel83/templight_binary/releases/download/templight_35f974_v2/templight_windows.zip
  - 7z -y x templight_windows.zip

before_build:
  - cd c:\projects\metashell
  - md bin
  - cd bin
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 12
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 12 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" ..

build:
  project: c:\projects\metashell\bin\metashell.sln
  parallel: true

test_script:
  - cd c:\projects\metashell\bin
  - test\unit\%configuration%\metashell_unit_test.exe
  - test\system\app\core\%configuration%\metashell_core_system_test.exe app\%configuration%\metashell.exe -- -I..\3rd\boost\include --
  - test\system\app\core\%configuration%\metashell_core_system_test.exe app\%configuration%\metashell.exe --engine clang -- app\%configuration%\templight\templight.exe -std=c++0x -ftemplate-depth=256 -Wfatal-errors -fno-ms-compatibility -U_MSC_VER -Iapp\%configuration%\windows_headers -Iapp\%configuration%\windows_headers\mingw32 -Iapp\%configuration%\templight\include -I..\3rd\boost\include --
  - test\system\app\pp\%configuration%\metashell_pp_system_test.exe app\%configuration%\metashell.exe -- -I..\3rd\boost\include --
  - test\system\app\pp\%configuration%\metashell_pp_system_test.exe app\%configuration%\metashell.exe --engine clang -- app\%configuration%\templight\templight.exe -std=c++0x -ftemplate-depth=256 -Wfatal-errors -fno-ms-compatibility -U_MSC_VER -Iapp\%configuration%\windows_headers -Iapp\%configuration%\windows_headers\mingw32 -Iapp\%configuration%\templight\include -I..\3rd\boost\include --
  - test\system\app\mdb\%configuration%\metashell_mdb_system_test.exe app\%configuration%\metashell.exe -- -I..\3rd\boost\include --
  - test\system\app\mdb\%configuration%\metashell_mdb_system_test.exe app\%configuration%\metashell.exe --engine clang -- app\%configuration%\templight\templight.exe -std=c++0x -ftemplate-depth=256 -Wfatal-errors -fno-ms-compatibility -U_MSC_VER -Iapp\%configuration%\windows_headers -Iapp\%configuration%\windows_headers\mingw32 -Iapp\%configuration%\templight\include -I..\3rd\boost\include --
