os: Visual Studio 2017

platform:
  - Win32

configuration:
  - Debug
  - Release

install:
  - cd 3rd\templight
  - appveyor DownloadFile https://github.com/metashell/templight_binary/releases/download/templight_9732a7/templight_windows.zip
  - 7z -y x templight_windows.zip
  - appveyor-retry choco install nsis -version 2.50.0.20160103
  - cd ..\..

before_build:
  - md bin
  - cd bin
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" ..
  - cd ..

build_script:
  - set NO_TEMPLIGHT=1
  - set METASHELL_NO_DOC_GENERATION=1
  - "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\" x86"
  - build.bat
