os: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug
  - Release

before_build:
  - cd c:\projects\metashell
  - md bin
  - cd bin
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 12
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 12 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ..

build:
  project: c:\projects\metashell\bin\metashell.sln
  parallel: true

test_script:
  - c:\projects\metashell\bin\test\unit\%configuration%\metashell_unit_test.exe
