site_name: Metashell
site_description: Template metaprogramming shell
site_dir: tools/demo_server/share/html
repo_url: https://github.com/metashell/metashell
use_directory_urls: false
pages:
    - Home: 'index.md'
    - Getting Metashell:
        - 'Supported platforms': 'getting_metashell/platforms.md'
        - 'Supported compilers': 'getting_metashell/compilers.md'
        - 'Binary installers': 'getting_metashell/installers.md'
        - 'Building Metashell': 'getting_metashell/build.md'
    - User manual:
        - 'Getting started': 'manual/getting_started.md'
        - 'The environment in Metashell': 'manual/environment.md'
        - 'Using different compilers': 'manual/compilers.md'
        - 'Troubleshooting': 'manual/troubleshooting.md'
        - 'Embedding Metashell': 'manual/embedding.md'
        - 'How to...' : 'manual/how_to.md'
    - Reference:
        - 'The pragmas': 'reference/pragmas.md'
        - 'MDB commands': 'reference/mdb_commands.md'
        - 'PDB commands': 'reference/pdb_commands.md'
        - 'The built-in headers': 'reference/headers.md'
        - 'Engines': 'reference/engines.md'
    - Developer guide:
        - 'Building Metashell': 'develop/build.md'
        - 'Creating a Metashell release': 'develop/release.md'
        - 'Testing Metashell': 'develop/testing.md'
        - 'Demo server': 'develop/demo_server.md'
        - 'Rationales': 'develop/rationales.md'
    - About:
        - 'Demo': 'about/demo.md'
        - 'Community': 'about/community.md'
        - 'Changelog': 'about/changelog.md'
theme: readthedocs

